/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.com.riko.andrew.order_statistic_with_Catagory;

import java.awt.Component;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JWindow;

import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 * 
 * @author andrew
 */
public class Order_Statistic extends javax.swing.JFrame {

	JWindow toolTip;
	Component preview;
	String start_day, end_day;
	static private Preferences preferences;
	boolean is_error = false;

	public Order_Statistic() {
		initComponents();
		jButton_open_file_chooser.setToolTipText("按此選擇檔案路徑");

		URL url = Order_Statistic.class.getResource("images/open.png");
		ImageIcon icon = new ImageIcon(url);
		// ImageIcon icon =(ImageIcon) jButton_open_file_chooser.getIcon();
		Image image = icon.getImage();
		Image newimg = image.getScaledInstance(
				jButton_open_file_chooser.getHeight() / 2, -1,
				java.awt.Image.SCALE_SMOOTH);
		icon.setImage(newimg);
		jButton_open_file_chooser.setIcon(icon);

		jLabel_waiting_picture.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("images/ajax-loader.gif")));

		// 以下隱藏目前做不到之控制項
		jLabel_DB1.setVisible(false);
		jComboBox_DB1.setVisible(false);
		//jLabel_DB.setVisible(false);
		//jComboBox_DB.setVisible(false);
		jLabel_waiting_picture.setVisible(false);

		this.getinit_Pref();

	}

	private void getinit_Pref() {
		// ///////////////////////////////////////////////////////////////////////////

		preferences = Preferences.userNodeForPackage(this.getClass());
		DateFormat formatter = new SimpleDateFormat("yyyyMMdd");

		// 設定初始日期為今天
		start_day = end_day = new SimpleDateFormat("yyyyMMdd").format(Calendar
				.getInstance().getTime());

		// 如果之前有用過,取得本機的前一次使用紀錄
		start_day = preferences.get("開始日期", start_day);
		end_day = preferences.get("結束日期", end_day);
		String file_path = preferences.get("檔案位置", "" );

		try {
			jDateChooser_start_DATE.setDate(formatter.parse(start_day));
			jDateChooser_end_DATE.setDate(formatter.parse(end_day));
			jTextArea_file_path.setText(file_path);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDateChooser_start_DATE = new com.toedter.calendar.JDateChooser();
		jDateChooser_end_DATE = new com.toedter.calendar.JDateChooser();
		jLabel_between_order = new javax.swing.JLabel();
		jLabel_start_order = new javax.swing.JLabel();
		jLabel_DB = new javax.swing.JLabel();
		jComboBox_DB = new javax.swing.JComboBox();
		jButton_open_file_chooser = new javax.swing.JButton();
		jLabel_start_order1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jComboBox_DB1 = new javax.swing.JComboBox();
		jLabel_DB1 = new javax.swing.JLabel();
		jTextArea_file_path = new javax.swing.JTextArea();
		jLabel_waiting_picture = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("銷售統計");
		setResizable(false);

		jLabel_between_order.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
		jLabel_between_order.setText("~");

		jLabel_start_order.setText("銷貨訂單日期：");

		jLabel_DB.setText("連接資料庫：");

		jComboBox_DB.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "測試", "力科", "永鉅" }));

		jButton_open_file_chooser
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton_open_file_chooserActionPerformed(evt);
					}
				});

		jLabel_start_order1.setText("檔案位置：");

		jButton1.setText("執行");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jComboBox_DB1.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "月", "季", "年" }));

		jLabel_DB1.setText("群組條件：");

		jTextArea_file_path.setEditable(false);
		jTextArea_file_path.setColumns(20);
		jTextArea_file_path.setLineWrap(true);
		jTextArea_file_path.setRows(5);
		jTextArea_file_path.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														330,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel_start_order1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jTextArea_file_path,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		252,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel_DB)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jComboBox_DB,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(86, 86,
																		86)
																.addComponent(
																		jLabel_DB1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jComboBox_DB1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		53,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel_start_order)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jButton_open_file_chooser,
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														50,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jDateChooser_start_DATE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		138,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addGap(18,
																																		18,
																																		18)
																																.addComponent(
																																		jLabel_between_order)
																																.addGap(18,
																																		18,
																																		18)
																																.addComponent(
																																		jDateChooser_end_DATE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		125,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addGap(33,
																																		33,
																																		33))))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(266,
																										266,
																										266)
																								.addComponent(
																										jLabel_waiting_picture)))))
								.addContainerGap(24, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(33, 33, 33)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jComboBox_DB,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel_DB)
												.addComponent(
														jComboBox_DB1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel_DB1))
								.addGap(37, 37, 37)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jDateChooser_start_DATE,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel_between_order,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														21,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jDateChooser_end_DATE,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel_start_order,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														21,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(42, 42,
																		42)
																.addComponent(
																		jLabel_start_order1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		21,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(28, 28,
																		28)
																.addComponent(
																		jButton_open_file_chooser,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jTextArea_file_path,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(34, 34,
																		34)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		61,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel_waiting_picture)))
								.addContainerGap(20, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jButton_open_file_chooserActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		File_Chooser choose = new File_Chooser();
		String file_path = choose.file_Read_Choose();
		jTextArea_file_path.setText(file_path);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		String message = "您輸入的日期格式不正確\n請輸入yyyy/mm/dd的格式";
		String title = "日期格式不正確";
		Calendar startCalendar = jDateChooser_start_DATE.getCalendar(), endCalendar = jDateChooser_end_DATE
				.getCalendar();

		final ArrayList<String> input_product_ID = this
				.get_input_product_IDs(jTextArea_file_path.getText());
		this.check_Date_Formate(startCalendar, endCalendar);

		if (is_error == false) {
			final String DB = jComboBox_DB.getSelectedItem().toString();

			new Thread(new Runnable() {

				@Override
				public void run() {
					// TODO Auto-generated method stub

					jLabel_waiting_picture.setVisible(true);
					jButton1.setEnabled(false);
					new Connect().conduct_Connect(start_day, end_day, DB,
							input_product_ID);
					jLabel_waiting_picture.setVisible(false);
					jButton1.setEnabled(true);

				}
			}).start();

		}

	}

	private ArrayList<String> get_input_product_IDs(String file_path) {
		ArrayList<String> input_product_ID = null;

		try {

			input_product_ID = new Read_Excel_with_Path().readExcel(file_path);
			if (input_product_ID == null) {
				is_error = true;
			}
		} catch (IOException ex) {
			ex.printStackTrace();
			JOptionPane.showMessageDialog(new JOptionPane(), "請確認指定檔案\n"
					+ file_path + "\n是否存在或沒有其他人正在使用", "無法讀取指定檔案",
					JOptionPane.ERROR_MESSAGE);
			is_error = true;
		} catch (InvalidFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (NullPointerException ex) {
			System.out
					.println("NullPointerException happens at Order_Statistic.get_input_product_IDs");
			ex.printStackTrace();
			JOptionPane.showMessageDialog(new JOptionPane(), "請確認指定檔案\n"
					+ file_path + "\n是否存在", "無法讀取指定檔案",
					JOptionPane.ERROR_MESSAGE);
			is_error = true;
		}

		return input_product_ID;
	}

	private void check_Date_Formate(Calendar startCalendar, Calendar endCalendar) {

		String message = "您輸入的日期格式不正確\n請輸入yyyy/mm/dd的格式";
		String title = "日期格式不正確";

		if (startCalendar != null & endCalendar != null) {
			if (endCalendar.getTimeInMillis() < startCalendar.getTimeInMillis()) {
				// 如果開始日期比較大,將開始日期與結束日期互換
				Calendar temp = startCalendar;
				startCalendar = endCalendar;
				endCalendar = temp;
				JOptionPane.showMessageDialog(new JOptionPane(), "開始日期要比結束日期小",
						"下次請注意", JOptionPane.WARNING_MESSAGE);
			}
			start_day = new java.text.SimpleDateFormat("yyyyMMdd")
					.format(startCalendar.getTime());
			end_day = new java.text.SimpleDateFormat("yyyyMMdd")
					.format(endCalendar.getTime());

			// 存開始日期跟結束日期到preferences中
			preferences.put("開始日期", start_day);
			preferences.put("結束日期", end_day);
			preferences.put("檔案位置", jTextArea_file_path.getText());
			
		} else if (startCalendar != null & endCalendar == null) {
			JOptionPane.showMessageDialog(new JOptionPane(), message, title,
					JOptionPane.ERROR_MESSAGE);
			is_error = true;
		} else if (startCalendar == null & endCalendar != null) {
			JOptionPane.showMessageDialog(new JOptionPane(), message, title,
					JOptionPane.ERROR_MESSAGE);
			is_error = true;
		} else {
			JOptionPane.showMessageDialog(new JOptionPane(), message, title,
					JOptionPane.ERROR_MESSAGE);
			is_error = true;
		}

	}

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Order_Statistic.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Order_Statistic.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Order_Statistic.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Order_Statistic.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Order_Statistic().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton_open_file_chooser;
	private javax.swing.JComboBox jComboBox_DB;
	private javax.swing.JComboBox jComboBox_DB1;
	private com.toedter.calendar.JDateChooser jDateChooser_end_DATE;
	private com.toedter.calendar.JDateChooser jDateChooser_start_DATE;
	private javax.swing.JLabel jLabel_DB;
	private javax.swing.JLabel jLabel_DB1;
	private javax.swing.JLabel jLabel_between_order;
	private javax.swing.JLabel jLabel_start_order;
	private javax.swing.JLabel jLabel_start_order1;
	private javax.swing.JLabel jLabel_waiting_picture;
	private javax.swing.JTextArea jTextArea_file_path;
	// End of variables declaration
}
